### ISSUE TITLE
Practica 5_Práctica Reconocimiento de patron Hiro

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/practica-de-marcador-hiro-equipo-nancy-brenda-belem#1]
[Practica 5_Práctica Reconocimiento de patron Hiro.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-marcador-hiro-equipo-nancy-brenda-belem/files/8597544/Practica.5_Practica.Reconocimiento.de.patron.Hiro.pdf)

**Comment by Jaci14** [comment]
La practica contiene todos los elementos pedidos en la rubrica, incluye portada, indice, ilustraciones, descripción etc.
Califocacion: 20%

**Comment by Jaci14** [comment]
La practica contiene todos los elementos pedidos en la rubrica, incluye portada, indice, ilustraciones, descripción etc.
Calificacion: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
